Fix regional weights-bug
openmodels/mimi-page-2020.jl pull request #35
Opened 2019-07-05 09:25 UTC by P-Wlich

This fixes the current bug that heterogenous regional damage weights for SLR and discontinuity end up being used for market and non-market damages as well, in contradiction to the PAGE-ICE excel file. To avoid that the weights are passed on between components, I named them separately following the PAGE-ICE excel where three different weights parameters are defined in the "Library Data" sheet.

As the weights for market and non-market damages are defined as Triangular(1, 1, 1) in the excel file, I did not include them into the mcs.jl file.

2019-07-07 11:18 UTC, jrising requested changes
Thanks for making these changes! Can you just move the parameter-setting code to the `add...` functions?

2019-07-07 11:18 UTC, jrising commented on src/components/MarketDamages.jl
> +            p.wincf_weightsfactor_market[r] = 1.
This should be set in the `addmarketdamages` function, not in `run_timestep`.

2019-07-07 11:18 UTC, jrising commented on src/components/MarketDamagesBurke.jl
> +            p.wincf_weightsfactor_market[r] = 1.
Same here.

2019-07-07 11:18 UTC, jrising commented on src/components/NonMarketDamages.jl
> +            p.wincf_weightsfactor_nonmarket[r] = 1.
Again.

2019-07-08 07:43 UTC, P-Wlich commented
Like this?

2019-07-09 08:23 UTC, jrising approved these changes
Looks good now. Go ahead and merge it. Thanks!

2019-07-09 09:57 UTC, merged